name: Python CI Pipeline

on:
  push:
    branches:
      - main  # Runs workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Runs on pull requests to the main branch

permissions:
  contents: read  

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10]  # Matches development version

    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure `flake8` and `pytest` are listed in requirements.txt

      # Linting with flake8
      - name: Run flake8 for linting
        run: |
          # This lints your repo for style issues and quality checks
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics  # Critical checks for errors
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      # Run unit tests with pytest
      - name: Run pytest for unit tests
        run: |
          pytest --disable-warnings --maxfail=1  # Runs tests and stops at the first failure
